### ISSUE TITLE
The hydralisk model is invisible

### ISSUE THREAD

**Issue by Adriborg8** [Onixiya/SC2Expansion#1]
Every single state of the hydralisk is invisible I've tried resetting btd6 but it's just invisible the next thing I'm gonna try is re-downloading the mod 
Edit: it didn't work

**Comment by Onixiya** [comment]
that sometimes happens for whatever reason and i have no idea why (only the hydralisk as well and no errors happen with it last time i tried to figure it out). i am currently in the middle of rewriting half the asset loading system to make it into one instead of a patch in every single towers file

**Comment by Adriborg8** [comment]
thanks, I guess this is a semi-common issue then. I wonder why no one had brought up the issue in the actual issues section before hand

**Comment by Adriborg8** [comment]
does this glitch occur on previous versions

**Comment by Onixiya** [comment]
using previous versions isn't recommended, you can try it if you want but there is a reason a new version is released
